export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  readTime: string;
  category: string;
  image: string;
  content: string;
}

export const posts: BlogPost[] = [
  {
    slug: "how-to-grow-cactus-from-seed",
    title: "How to Grow Cactus From Seed: A Beginner's Guide",
    excerpt: "Growing cactus from seed requires patience, but it's worth the effort. Here's everything you need to know to get started with sterile soil, humidity control, and proper light.",
    date: "July 18, 2026",
    readTime: "6 min read",
    category: "Growing Tips",
    image: "/cactus-logo.png",
    content: `Starting cactus from seed is one of the best parts of plant collecting. Unlike purchasing mature plants, growing from seed lets you watch every stage of development — from a tiny green speck to a robust, mature cactus.\n\n**What You'll Need**\n\n- Sterile cactus soil mix (or make your own with perlite, pumice, and fine sand)\n- Shallow containers with drainage holes\n- Clear humidity dome or plastic wrap\n- Spray bottle for misting\n- Warm location with indirect sunlight (25-28°C / 77-82°F)\n\n**Step-by-Step Process**\n\n1. Fill your container with pre-moistened soil mix. The soil should be damp, not waterlogged.\n2. Scatter seeds evenly across the surface. Do not bury them — cactus seeds need light to germinate.\n3. Mist the surface gently and cover with a humidity dome or plastic wrap.\n4. Place in a warm spot with bright, indirect light. Direct sunlight will cook seedlings.\n5. Mist daily to maintain humidity. Open the dome for 10 minutes every few days to prevent mold.\n6. Expect germination in 7-21 days depending on species.\n\n**Common Mistakes**\n\n- Overwatering: soggy soil causes damping off (seedling collapse)\n- Too much sun: seedlings are far more delicate than mature plants\n- Using regular potting soil: it retains too much moisture and harbors pathogens\n\nBe patient. Cactus seedlings are slow growers, but each tiny pad is a victory.`,
  },
  {
    slug: "best-cactus-soil-mix",
    title: "The Best Soil Mix for Cactus and Succulents",
    excerpt: "Not all soil is created equal. Learn why well-draining soil is critical for cactus health and how to mix the perfect substrate at home.",
    date: "July 12, 2026",
    readTime: "5 min read",
    category: "Plant Care",
    image: "/cactus-logo.png",
    content: `The number one cause of cactus death isn't neglect — it's root rot from poor soil. Cacti evolved in rocky, sandy desert environments where water drains away almost immediately. Replicating that at home is the key to healthy roots.\n\n**The Ideal Mix**\n\nA great cactus soil has three components:\n\n- **Gritty material** (50%): pumice, perlite, or coarse sand — creates air pockets and drainage\n- **Organic material** (30%): coconut coir or peat-free compost — provides nutrients\n- **Fine aggregate** (20%): small gravel or akadama — adds weight and stability\n\n**Why Store-Bought "Cactus Soil" Isn't Enough**\n\nMost commercial cactus mixes still hold too much water. They're a starting point, not a solution. Always amend with extra perlite or pumice (at least 1:1 ratio with the mix).\n\n**Signs Your Soil Is Too Heavy**\n\n- Water sits on the surface after watering\n- Soil stays wet for more than 3-4 days\n- Roots appear brown or mushy\n- Plant base softens or discolors\n\nRepotting into proper soil is the single best thing you can do for your cactus.`,
  },
  {
    slug: "common-cactus-pests",
    title: "Common Cactus Pests and How to Deal With Them",
    excerpt: "Even the toughest desert plants face threats from pests. Learn to identify and treat the most common issues before they spread to your collection.",
    date: "July 5, 2026",
    readTime: "5 min read",
    category: "Plant Care",
    image: "/cactus-logo.png",
    content: `Cacti are hardy plants, but they're not immune to pests. Mealybugs, spider mites, and scale are the most common invaders — and they can devastate a collection if left unchecked.\n\n**Mealybugs**\n\nWhite, cotton-like clusters in the joints and roots of your cactus. They suck sap and secrete honeydew, which attracts ants and promotes fungal growth.\n\nTreatment: Dab with 70% isopropyl alcohol using a cotton swab. For heavy infestations, spray with neem oil solution weekly.\n\n**Spider Mites**\n\nTiny red or brown dots on the surface with fine webbing between spines. Leaves and stems appear stippled or bronze.\n\nTreatment: Spray the entire plant with water to dislodge mites, then apply neem oil or insecticidal soap. Isolate the plant immediately.\n\n**Scale Insects**\n\nBrown or tan bumps that look like part of the plant's skin. They're actually armored insects feeding on sap.\n\nTreatment: Scrape off gently with a soft brush, then apply rubbing alcohol. Repeat weekly until clear.\n\n**Prevention Tips**\n\n- Inspect new plants thoroughly before introducing them to your collection\n- Quarantine new additions for 2 weeks\n- Maintain good airflow around plants\n- Avoid overwatering — stressed plants attract more pests`,
  },
  {
    slug: "watering-cactus-guide",
    title: "How to Water Cactus Plants Properly",
    excerpt: "Watering seems simple, but it's the most common place where cactus care goes wrong. Here's the right way to water — and when to stop.",
    date: "June 28, 2026",
    readTime: "4 min read",
    category: "Growing Tips",
    image: "/cactus-logo.png",
    content: `The golden rule of cactus watering: when in doubt, don't water. Cacti store water in their stems and roots, and they're built to survive drought. Overwatering kills far more cacti than underwatering.\n\n**The Soak-and-Dry Method**\n\n1. Check if the soil is completely dry by inserting a wooden stick 2 inches into the soil. If it comes out clean and dry, water.\n2. Water thoroughly until it runs out the drainage holes.\n3. Allow all excess water to drain completely.\n4. Don't water again until the soil is bone dry throughout.\n\n**Seasonal Adjustments**\n\n- **Spring/Summer** (growing season): Water every 1-2 weeks, depending on heat and light\n- **Fall**: Reduce to every 3-4 weeks as growth slows\n- **Winter** (dormancy): Water once a month or not at all. Many species rest completely\n\n**Signs of Overwatering**\n\n- Soft, translucent stems\n- Black or brown spots at the base\n- Mushy roots when checked\n- Fungus gnats around the soil\n\n**Signs of Underwatering** (less common)\n\n- Wrinkled or shriveled stems\n- Plant pulling away from the soil\n- Dry, crispy roots\n\nWhen in doubt, underwater. Your cactus will forgive you for drought. It won't forgive you for rot.`,
  },
  {
    slug: "why-sustainable-cactus-trade-matters",
    title: "Why Sustainable Cactus Trade Matters",
    excerpt: "The demand for rare cacti is rising. Here's how ethical growers are protecting wild populations while meeting collector demand.",
    date: "June 20, 2026",
    readTime: "6 min read",
    category: "Ethics & Sustainability",
    image: "/cactus-logo.png",
    content: `Wild cactus populations are under threat. Habitat loss, climate change, and illegal collection have pushed many species to the brink. The rise of online plant sales has made rare species more accessible — but it's also created a shadow market for wild-harvested specimens.\n\n**The Problem**\n\nMany rare cacti — particularly Lophophora and Astrophytum species — are collected from the wild and sold as "collected" or "wild-grown" specimens. These plants can be 20-50 years old, and removing them from their habitat is devastating to local ecosystems.\n\n**How Ethical Growers Help**\n\n- **Greenhouse propagation**: Growing from seed eliminates the need for wild collection\n- **Tissue culture**: Lab-grown specimens produce identical plants without touching wild populations\n- **Seed exchange**: Collectors sharing seeds reduces demand for wild-collected plants\n\n**What You Can Do**\n\n1. Always ask whether a plant is greenhouse-grown or wild-collected\n2. Buy seeds rather than mature plants when possible\n3. Support nurseries that are transparent about their sourcing\n4. Never collect wild cacti yourself — it's illegal in most jurisdictions\n\nThe cactus community has a responsibility to protect the species we love. Every greenhouse-grown plant is one less taken from the wild.`,
  },
  {
    slug: "how-long-do-cactus-seeds-take-to-germinate",
    title: "How Long Do Cactus Seeds Take to Germinate?",
    excerpt: "From a few days to a few months — germination times vary wildly across cactus species. Here's a realistic timeline and how to speed things up.",
    date: "August 2, 2026",
    readTime: "5 min read",
    category: "Growing Tips",
    image: "/cactus-logo.png",
    content: `If you've just sprinkled your first batch of cactus seeds, the wait can feel endless. The truth is that germination times vary enormously between species — some pop in under a week, while others need months and a cold winter to wake up.\n\n**Fast Germinators (5-14 days)**\n\n- Mammillaria and rebutia species\n- Most Ferocactus and Echinocactus\n- Gymnocalycium\n\nThese are the most rewarding for beginners. Sow in warm conditions and you'll usually see green within two weeks.\n\n**Medium Germinators (2-6 weeks)**\n\n- Most Astrophytum varieties\n- Many Trichocereus and Echinopsis\n- Turbinicarpus\n\nThese need steady warmth and bright light. Patience pays off — keep the humidity dome on and resist peeking.\n\n**Slow and Stubborn (1-3 months or longer)**\n\n- Ariocarpus and Aztekium\n- Some Discocactus and Melocactus\n- Species from cold high-altitude deserts\n\nSome of these actually need stratification: a cool period (around 4-6 weeks at 4-8°C) before they'll germinate. Others just need time and consistency.\n\n**How to Speed Up Germination**\n\n1. Soak seeds in warm water for 24 hours before sowing\n2. Use a heat mat to keep the soil at a steady 25-28°C\n3. Keep a tight humidity dome — seeds need 90%+ humidity to germinate\n4. Provide bright indirect light, never direct sun\n\n**When to Give Up**\n\nDon't throw the tray out too soon. Many growers report seedlings appearing 4-6 months after sowing in species known for being slow. As long as the soil isn't rotting, keep the tray humid and warm.\n\nEvery species has its own clock. Learning that timing is one of the most satisfying parts of growing cacti from seed.`,
  },
  {
    slug: "why-is-my-cactus-turning-yellow",
    title: "Why Is My Cactus Turning Yellow? 7 Common Causes and Fixes",
    excerpt: "A yellowing cactus is almost always trying to tell you something. Diagnose the cause before you water — here are the 7 most common culprits.",
    date: "July 26, 2026",
    readTime: "5 min read",
    category: "Plant Care",
    image: "/cactus-logo.png",
    content: `Yellowing on a cactus rarely means "it needs more water" — in fact, the opposite is usually true. Here are the most common causes, from most to least frequent.\n\n**1. Overwatering and Root Rot**\n\nThe number one cause. Yellowing that starts at the base and creeps upward, often with a soft, mushy texture, means the roots are drowning. Stop watering immediately, let the soil dry completely, and repot into a gritty mix if the base feels soft.\n\n**2. Too Much Direct Sunlight**\n\nA cactus moved suddenly from shade to full sun will bleach and turn yellow or pale. Introduce sun gradually over 2-3 weeks. Some species are naturally shade-tolerant and want bright light, not direct afternoon sun.\n\n**3. Too Little Light**\n\nYellowing plus stretching and thinning growth (etiolation) means the plant is reaching for light. Move it to a brighter spot or add a grow light.\n\n**4. Nutrient Deficiency**\n\nA general, uniform yellowing can mean a lack of nitrogen. Feed with a balanced cactus fertilizer diluted to half strength during the growing season.\n\n**5. Rootbound or Stale Soil**\n\nIf a cactus hasn't been repotted in years, the soil becomes compacted and depleted. Repot in spring with fresh gritty mix.\n\n**6. Cold Damage**\n\nSudden yellowing after a cold snap usually means tissue damage. Move the plant somewhere warmer; damaged tissue won't recover, but the plant may push new growth.\n\n**7. Natural Aging**\n\nOlder cacti naturally cork at the base — a hard, brownish-yellow bark forms over time. That's normal, not a disease.\n\n**How to Diagnose**\n\nCheck the soil first. Wet and soggy? Overwatering. Dry and rock-hard for weeks? Possibly underwatering or rootbound. Feel the base — soft means rot, firm means sun or nutrient issues.\n\nMost yellowing cacti can be saved with one change: let the soil dry out, move the plant, or repot. Act early and your cactus will usually bounce back.`,
  },
  {
    slug: "how-to-repot-a-cactus",
    title: "How to Repot a Cactus Without Getting Pricked",
    excerpt: "Repotting doesn't have to be a painful experience. Here's the safe, step-by-step method pros use — tools included.",
    date: "July 20, 2026",
    readTime: "4 min read",
    category: "Plant Care",
    image: "/cactus-logo.png",
    content: `Every cactus eventually needs repotting — for fresh soil, a bigger pot, or to treat rot. Here's how to do it with zero punctures.\n\n**Tools You'll Need**\n\n- Thick leather or rubberized gardening gloves\n- Kitchen tongs or a folded newspaper sling\n- A new pot with drainage holes, 1-2cm wider than the current one\n- Fresh gritty cactus soil\n- Chopstick or pencil for tamping\n\n**Step-by-Step**\n\n1. Stop watering 5-7 days before repotting. Dry soil holds its shape and won't tear roots.\n2. Tilt the pot and slide the cactus out using tongs or a newspaper sling wrapped around the body.\n3. Gently tease off old soil from the roots. Remove any black or mushy roots with clean scissors.\n4. Let the roots air-dry for 2-3 days. This allows any root damage to callus over and prevents rot.\n5. Add fresh soil to the new pot, position the cactus, and backfill. Use a chopstick to work soil between roots.\n6. Wait another 5-7 days before the first watering. This lets any root nicks heal.\n\n**Pro Tips**\n\n- Never grip a cactus directly with bare hands — spines can be microscopic and barbed\n- If the plant is too big for tongs, roll it onto a folded towel and carry it that way\n- Water the edge of the pot, not the crown, for the first few weeks\n- Repot in spring or early summer, when the plant is actively growing\n\nRepotting is the best way to refresh a tired cactus. Once you've done it a few times, it's a 10-minute job.`,
  },
  {
    slug: "best-cactus-varieties-for-beginners",
    title: "Best Cactus Varieties for Beginners: Low-Maintenance Favorites",
    excerpt: "Not all cacti are created equal for new growers. Start with these forgiving species that tolerate beginner mistakes and still look spectacular.",
    date: "July 14, 2026",
    readTime: "5 min read",
    category: "Buying Guide",
    image: "/cactus-logo.png",
    content: `If you're new to cacti, choosing the right first plants is the difference between a rewarding hobby and a shelf of sad, brown mush. These species forgive mistakes.\n\n**Mammillaria**\n\nThe workhorses of the cactus world. Hundreds of species, all small, free-flowering, and tolerant of neglect. They shrug off missed waterings and bloom reliably every spring.\n\n**Gymnocalycium**\n\nRounded, spineless-or-fine-spined, and constantly flowering. Their flowers open in waves through summer. Perfect indoors because they don't need intense sun.\n\n**Rebutia**\n\nClump-forming miniatures with spectacular flowers that can cover the whole plant. They're cold-tolerant and bloom young — often within a year or two of sowing.\n\n**Ferocactus**\n\nThe classic barrel cactus. Bold, architectural, and almost impossible to kill. Give it plenty of sun and it thrives.\n\n**Echinopsis**\n\nFast-growing, generous flowerers, and very forgiving. They take overwatering better than most — a good trait for new growers.\n\n**What Beginners Should Avoid (for now)**\n\n- **Ariocarpus**: stunning but extremely slow and sensitive to overwatering\n- **Astrophytum asterias**: beautiful, but demanding about water and light\n- **Any small grafted cactus**: colorful, but the base stock is finicky\n\n**A Starter Routine That Works**\n\n1. Bright, indirect light for most species; direct sun only for barrels\n2. Water when completely dry — roughly every 1-2 weeks in summer, monthly or less in winter\n3. Repot every 2-3 years into gritty soil\n4. Fertilize lightly from spring to late summer\n\nStart with three or four of the easy species above, learn their rhythms, and your confidence — and collection — will grow fast.`,
  },
  {
    slug: "damping-off-cactus-seedlings",
    title: "Damping Off in Cactus Seedlings: Signs, Causes & Prevention",
    excerpt: "Seedlings collapsing overnight are a heartbreaking sight. Here's how to spot damping off early, what causes it, and how to stop it before it wipes out your tray.",
    date: "August 4, 2026",
    readTime: "5 min read",
    category: "Growing Tips",
    image: "/cactus-logo.png",
    content: `You check on your seedlings in the morning and a whole section has fallen over — tiny stems pinched, brown, and lying flat. That's damping off, a fungal disease that's the most common killer of cactus seedlings. The good news: it's almost entirely preventable.\n\n**What Damping Off Looks Like**\n\n- Seedlings fall over at the base while the top still looks green\n- A thin, water-soaked, or brown ring at the soil line\n- White or gray mold fuzz spreading across the soil surface\n- Seedlings that were fine at night are gone by morning\n\nIt strikes fast because the fungi (Pythium, Fusarium, Rhizoctonia) attack the stem right at the soil line, cutting off the plant from its roots.\n\n**The 4 Root Causes**\n\n1. **Too much moisture**: constantly wet soil is the perfect breeding ground\n2. **Poor airflow**: a sealed humidity dome with no ventilation breeds mold\n3. **Unsterile soil**: reused or garden soil carries fungal spores\n4. **Crowding**: seedlings packed too tightly trap humidity at the base\n\n**Prevention (far easier than cure)**\n\n- Use fresh, well-draining soil — never garden soil, never reused\n- Water from below or with a fine mist, keeping the surface from staying soggy\n- Open the humidity dome for 10-15 minutes daily to exchange air\n- Remove dead or fallen seedlings immediately — they seed the next infection\n- Consider a light dusting of sulfur or cinnamon powder on the soil surface before sowing\n\n**If It Appears**\n\nAct fast: remove every affected seedling and the soil around it, increase airflow dramatically, and let the surface dry slightly between waterings. Seedlings in a separate pot can sometimes be rescued by scooping them with a spoon of clean soil and transplanting.\n\nPrevention beats rescue every time. A clean tray with good airflow rarely sees damping off at all.`,
  },
  {
    slug: "how-to-harden-off-cactus-seedlings",
    title: "How to Harden Off Cactus Seedlings (Step-by-Step)",
    excerpt: "Moving seedlings straight from a humid dome to open air is a death sentence. Learn the gradual hardening-off process that gives your young cacti a real chance.",
    date: "August 3, 2026",
    readTime: "5 min read",
    category: "Growing Tips",
    image: "/cactus-logo.png",
    content: `Your cactus seeds have germinated, the tray is lush, and it's time to take the dome off. Hold on. Seedlings raised under a humidity dome are soft, and open air will shock them — they can collapse within a day. Hardening off is the gradual transition that prevents this.\n\n**Why It's Necessary**\n\nUnder the dome, humidity stays near 90%+, so seedlings never develop a proper cuticle (their waxy protective layer). Exposed suddenly to 40-50% room air, they lose water faster than their tiny roots can replace it.\n\n**The Step-by-Step Process**\n\n1. **Crack the dome** — prop it open 1-2cm for a few days. Humidity drops slightly, airflow begins.\n2. **Remove the dome for hours** — take it off for 1-2 hours daily, then replace. Increase by an hour every couple of days.\n3. **Full removal** — after 1-2 weeks of gradual exposure, leave the dome off completely during the day.\n4. **Brighten gradually** — while hardening off, move the tray toward stronger light slowly. Direct sun still burns young seedlings.\n5. **Water accordingly** — with humidity gone, the soil dries faster. Water when the surface is nearly dry, not on a schedule.\n\n**When to Start**\n\nBegin hardening off when seedlings are big enough to have a visible body — typically 4-8 weeks after germination, once they've grown past the delicate 'green speck' stage.\n\n**Common Mistakes**\n\n- Rushing it: patience over 1-2 weeks beats a single bad afternoon\n- Skipping airflow while the dome is still on (mold risk)\n- Moving to full sun immediately after dome removal\n- Letting soil dry out completely during the transition\n\nHardening off is the bridge between the protected nursery and the real world. Do it gradually and your seedlings will thrive once they're on their own.`,
  },
  {
    slug: "cactus-winter-dormancy-guide",
    title: "Cactus Winter Dormancy: Watering, Light & Temperature",
    excerpt: "Most cacti need a cool, dry winter rest to flower and stay healthy. Here's exactly how to adjust watering, temperature, and light from fall through spring.",
    date: "August 2, 2026",
    readTime: "6 min read",
    category: "Plant Care",
    image: "/cactus-logo.png",
    content: `In nature, cacti experience a distinct dry season each year. Recreating that winter rest indoors is the difference between a cactus that survives and one that thrives and flowers. Here's how dormancy works and how to manage it.\n\n**What Dormancy Is**\n\nAs daylight shortens and temperatures drop, most cacti stop growing and enter a resting phase. They shut down root activity and live off stored water. For many species — especially Astrophytum, Echinopsis, and the flowering columnars — a proper winter rest is required to set flower buds for the next season.\n\n**Watering: The Most Important Rule**\n\n- Stop fertilizing entirely in late fall\n- Reduce watering gradually through fall, letting soil stay dry longer between drinks\n- In true winter dormancy, water sparingly — once every 4-6 weeks, or not at all for many species\n- Keep the soil bone dry between those rare waterings; wet roots at cold temperatures rot quickly\n\n**Temperature**\n\n- Ideal dormant range for most cacti: 5-12°C (41-54°F)\n- A cool room, unheated spare room, or garage window works\n- Avoid frost — few cacti tolerate freezing\n- If you can't provide cool temperatures, compensate by keeping the plant very dry\n\n**Light**\n\n- Keep cacti in the brightest spot you have\n- Dormant cacti need light, even if they're not growing — weak light plus cool temps causes etiolation later\n- A cool window with strong indirect light is the classic winter spot\n\n**When to Wake Them**\n\nIn early spring, increase watering slowly and raise temperatures. Don't flood a dormant plant — start with a light watering, then resume normal routine once you see new growth.\n\n**Species That Skip Dormancy**\n\nSeedlings, grafted plants, and a few tropical genera keep growing year-round. Young seedlings in particular should stay warm and lightly watered through winter — let them grow. It's mature plants that need the rest.\n\nA cool, dry, bright winter is one of the kindest things you can do for a mature cactus. It sets the stage for healthy growth and flowers all summer.`,
  },
  {
    slug: "how-to-germinate-lophophora-peyote-seeds",
    title: "How to Germinate Lophophora (Peyote) Seeds: A Step-by-Step Guide",
    excerpt: "Peyote is one of the slowest and most rewarding cacti to grow from seed. Here's the exact method — temperature, humidity, and light — that gets Lophophora seeds to germinate.",
    date: "August 9, 2026",
    readTime: "6 min read",
    category: "Growing Tips",
    image: "/cactus-logo.png",
    content: `Lophophora williamsii — the peyote cactus — has a reputation for being difficult to grow from seed. In reality, the seeds aren't hard to germinate; they just need specific conditions and serious patience afterward. Get the first three months right and you'll have a tiny button cactus that will outlive you.\n\n**Before You Start**\n\n- Seeds should be fresh — Lophophora germination rates drop noticeably after a year or two of storage\n- You'll need a sterile, gritty soil mix (50% fine perlite/pumice, 50% mineral sand or crushed granite — little to no organic matter)\n- A sealed container or baggie method works best because it locks in humidity\n- Bottom heat is almost essential for consistent results\n\n**Step 1: Prepare the Container**\n\nUse a small pot or seed tray with drainage, or the baggie method: moisten the soil lightly, sow the seeds, and seal the whole pot inside a clear plastic bag. The sealed bag keeps humidity near 100% and prevents the soil from drying out for weeks.\n\n**Step 2: Sow on the Surface**\n\nLophophora seeds are tiny. Scatter them on the surface and press them gently into the soil — do not bury them. They need light to trigger germination.\n\n**Step 3: Provide Bottom Heat**\n\nThis is the single biggest factor. Keep the soil at a steady 26-30°C (79-86°F) with a heat mat. At room temperature alone, germination is erratic and can drag on for weeks. With heat, you'll see the first green within 5-14 days.\n\n**Step 4: Keep Them Bright, Not Hot**\n\nPlace the sealed container in bright, indirect light. A windowsill with morning sun or a grow light a few inches away works. Direct hot sun inside a sealed bag will cook the seedlings — keep temperatures under 32°C.\n\n**Step 5: Be Patient With Germination**\n\nMost seeds pop within 2-3 weeks, but it's normal for stragglers to appear over the following month. Keep the bag sealed until the majority have germinated.\n\n**After Germination**\n\n- Slowly open the bag over a week or two to reduce humidity (see hardening off — the same principle applies)\n- Lophophora seedlings grow painfully slowly; after a full year you may only have pea-sized buttons\n- Water sparingly once the dome is off — let the surface dry between waterings\n- Don't fertilize for the first 6-12 months; seedlings get everything from the seed and soil\n\n**Common Mistakes**\n\n- Burying seeds: they won't germinate without light at the surface\n- No bottom heat: germination becomes slow and unreliable\n- Keeping the bag sealed too long after germination: causes mold and damping off\n- Transplanting too early: wait until buttons are at least pea-sized\n\nGrowing Lophophora from seed isn't quick — but watching a tiny button form where a seed sat is one of the most satisfying things in cactus growing.`,
  },
  {
    slug: "how-to-graft-cactus-seedlings",
    title: "How to Graft Cactus Seedlings: Fast-Track Slow Growers",
    excerpt: "Grafting a tiny seedling onto a vigorous rootstock turns a decade-long wait into a one-year payoff. Here's the full method — tools, technique, and aftercare.",
    date: "August 9, 2026",
    readTime: "6 min read",
    category: "Growing Tips",
    image: "/cactus-logo.png",
    content: `Some cacti — like Lophophora, Ariocarpus, and young Astrophytum — grow so slowly from seed that collectors wait years just for a marble-sized plant. Grafting solves this: by splicing a seedling onto a fast-growing rootstock like Pereskiopsis or Trichocereus, the scion grows at the rootstock's speed. A 12-month graft can outpace a 5-year own-root seedling.\n\n**Why Grafting Works**\n\nGrafted plants share the rootstock's vigorous root system and photosynthesis capacity. The scion (top) keeps its own genetics and appearance, but suddenly has the plumbing of a much larger plant.\n\n**What You'll Need**\n\n- A vigorous rootstock: Pereskiopsis (best for tiny seedlings), Trichocereus or Echinopsis (better for larger grafts), or Hylocereus (dragon fruit) for fast growers\n- A very sharp, clean blade — a scalpel or razor blade; sterility is critical\n- Disinfected tools (wipe with 70% alcohol between cuts)\n- Rubber bands, grafting clips, or soft string to hold the pieces together\n- A plastic bag or humidity dome for aftercare\n\n**The Method (Seedling Graft)**\n\n1. Cut the rootstock flat about 1-2cm below its growing tip. The cut surface must be perfectly horizontal and clean.\n2. Bevel the edge of the cut (trim a thin ring off the rim) so it doesn't sink inward as it dries.\n3. Slice the seedling horizontally through its widest point, about halfway up. The larger the cut surface, the better the union.\n4. Place the seedling cut-side-down directly on the rootstock's cut surface. They must align — the vascular rings need to overlap.\n5. Gently press with a clean finger to expel air bubbles.\n6. Hold the scion in place with a soft rubber band stretched over the top (avoiding the scion itself) or a light wrap of plumber's tape. Don't squeeze — you want contact, not pressure damage.\n7. Cover the whole plant with a clear plastic bag or humidity dome for 7-14 days to prevent the scion from drying out.\n\n**Aftercare**\n\n- Keep the graft in bright, indirect light for the first 1-2 weeks — no direct sun\n- After the union sets (check gently after ~2 weeks), remove the bag and band\n- A firm, unshrunken scion that's visibly growing means success\n- If the scion shrivels or falls off, re-cut and try again — grafting is a numbers game\n\n**Common Grafting Mistakes**\n\n- Dull or dirty blades: causes rot at the cut line\n- Misaligned vascular rings: the union never connects\n- Letting the scion dry out: humidity aftercare is essential\n- Cutting too slowly or crushing the tissue with blunt pressure\n\n**When Grafting Makes Sense**\n\n- Speeding up notoriously slow species (Lophophora, Ariocarpus, Aztekium)\n- Saving a seedling with root problems — graft it and it lives\n- Producing offsets from a prized plant faster\n- Recovering a rotted specimen by grafting its healthy top\n\nTry a few grafts with seedlings you can spare. Once you master the union, you'll never wait a decade for a slow cactus again.`,
  },
  {
    slug: "why-is-my-cactus-mushy",
    title: "Why Is My Cactus Mushy? Root Rot and Soft Base Explained",
    excerpt: "A soft, squishy cactus base is almost always rot — and the clock is ticking. Here's how to tell rot from harmless corking, and how to save a mushy cactus fast.",
    date: "August 9, 2026",
    readTime: "5 min read",
    category: "Plant Care",
    image: "/cactus-logo.png",
    content: `You squeeze your cactus near the soil line and it gives way like a bruised peach. That softness is bad news — it usually means rot, and rot spreads fast. But not every soft spot is a death sentence. Here's how to diagnose and act.\n\n**Mushy vs. Corking: Know the Difference**\n\n- **Corking** (normal): a firm, dry, brown or woody base that develops as cacti age. It feels hard, like bark. No action needed.\n- **Rot** (danger): soft, squishy, often discolored, sometimes oozing or smelling foul. If the base gives under light pressure, it's rot.\n\n**What Causes a Mushy Cactus**\n\n1. **Overwatering** — by far the most common. Wet soil suffocates roots, and fungi (Fusarium, Phytophthora) take over.\n2. **Cold plus wet** — roots watered at low temperatures rot even faster.\n3. **Poor drainage** — heavy soil holds water at the base for days.\n4. **Damage or sunburn** — a wound lets fungi enter the stem.\n5. **Too-deep planting** — the buried stem stays damp and rots.\n\n**Is It Mushy From the Base Up?**\n\nRot almost always starts in the roots or at the soil line and climbs. If the softness is high up on the body with a firm base, that's more likely sunburn, cold damage, or bruising — a different problem.\n\n**How to Save a Mushy Cactus (Immediate Action)**\n\n1. **Stop watering immediately.** Let the soil dry completely.\n2. **Unpot it.** Gently remove the plant and inspect the roots and base.\n3. **Cut away all soft tissue.** With a sterile knife, slice up the stem until you reach firm, healthy, white or green tissue. This is non-negotiable — leaving any rot means it spreads.\n4. **Let the wound callus.** Leave the cut surface in a dry, airy spot for 1-2 weeks until a hard callus forms. No soil, no water.\n5. **Re-root or graft.** Once callused, pot the top in dry, gritty soil and wait — many cacti push new roots from the cut. If the remaining piece is tiny, graft it onto a vigorous rootstock to save it.\n6. **Water sparingly.** Wait 1-2 weeks after potting, then water lightly and only when the soil is completely dry.\n\n**Prevention**\n\n- Use a gritty, fast-draining mix — never garden soil\n- Water only when the soil is bone dry, especially in winter\n- Keep the base above the soil line when planting\n- Repot every 2-3 years to refresh soil and inspect roots\n- Keep plants warm in winter; cold + wet = rot\n\nA mushy cactus can usually be saved if you act the day you notice it. The longer it sits, the higher the rot climbs — so don't wait.`,
  },
  {
    slug: "how-to-grow-trichocereus-from-seed",
    title: "How to Grow Trichocereus (San Pedro) From Seed",
    excerpt: "Trichocereus are some of the fastest, most rewarding cactus species to grow from seed — most reach a foot tall in 2-3 years. Here's the complete method.",
    date: "August 9, 2026",
    readTime: "5 min read",
    category: "Growing Tips",
    image: "/cactus-logo.png",
    content: `Trichocereus (now often classified as Echinopsis) — including the classic San Pedro — are the perfect beginner's seed-grown columnar cacti. Unlike most cacti, they grow fast, tolerate more moisture, and reward you with dramatic vertical growth within a couple of years.\n\n**Why Grow Trichocereus From Seed**\n\n- Fastest-growing of the popular cactus genera — seedlings can double in size within months\n- Far cheaper than buying mature cuttings\n- Seeds produce genetic variety: flower color and growth form vary seedling to seedling\n- Forgiving of beginner mistakes compared to Lophophora or Ariocarpus\n\n**What You'll Need**\n\n- Fresh Trichocereus seeds (viable for years when stored dry and cool)\n- A standard gritty cactus mix with some organic content — Trichocereus like a bit more compost than desert cacti\n- A seed tray or pot with drainage, plus a humidity dome or plastic bag\n- A heat mat (optional but helpful) and bright, indirect light\n\n**Sowing**\n\n1. Moisten the soil mix thoroughly before sowing — it should be damp, not dripping.\n2. Scatter seeds on the surface and press lightly. Don't bury them.\n3. Seal with a humidity dome or bag.\n4. Keep at 22-28°C (72-82°F) in bright, indirect light.\n\n**Germination**\n\nMost Trichocereus germinate within 7-21 days, and germination rates are typically high with fresh seed — often 80%+. You'll see a carpet of green within a few weeks.\n\n**After Germination**\n\n- Keep the dome sealed until most seedlings are well established, then harden them off gradually\n- Once the dome is off, water when the surface dries — Trichocereus seedlings like consistent moisture, but the soil still needs to drain fast\n- Grow them warm and bright through the growing season\n\n**Growth Expectations**\n\n- Year 1: a small, neat seedling — often 1-3cm\n- Year 2-3: real vertical growth begins, and fast-growing types can reach 30-60cm\n- Flowers: usually 3-5 years from seed, sometimes sooner with a strong summer\n\n**Winter Care for Young Plants**\n\nKeep young Trichocereus warmer and slightly moister than mature cacti in winter. They'll slow down but shouldn't fully dry-freeze. Mature plants tolerate cool, dry dormancy well.\n\n**Common Problems**\n\n- Damping off in the sealed tray — open the dome for ventilation regularly\n- Slow growth from too little light — give them the brightest spot you can\n- Stretching (etiolation) — a sign they want more light\n\nTrichocereus is the cactus that makes seed-growing feel fast. Sow a tray, and in a few seasons you'll have a small forest of columns.`,
  },
  {
    slug: "growing-cactus-indoors-grow-lights",
    title: "Growing Cactus Indoors Under Grow Lights",
    excerpt: "Most indoor cacti fail because windowsills just aren't bright enough. Here's how to choose, position, and run grow lights so your cacti stay compact, healthy, and flowering.",
    date: "August 9, 2026",
    readTime: "6 min read",
    category: "Plant Care",
    image: "/cactus-logo.png",
    content: `Most indoor cacti don't die from neglect — they die slowly from light starvation. A windowsill, even a bright one, delivers a fraction of the sunlight a desert cactus needs. That's why so many indoor cacti stretch into pale, skinny versions of themselves. Grow lights fix this completely.\n\n**The Problem With Windows**\n\n- Glass filters out much of the useful light\n- Most cacti need 6+ hours of direct-equivalent sun daily — rare indoors\n- Winter daylight in the northern hemisphere is weak even in south windows\n\nThe symptoms of too little light: pale green, elongated growth (etiolation), weak new spines, no flowering, and a plant that leans toward the window.\n\n**What to Look For in a Grow Light**\n\n- **Full-spectrum LED** is best for cacti — it mimics sunlight and keeps growth compact\n- **White/neutral light** (5000-6500K) works better than pink blurple for everyday viewing\n- **Output matters more than wattage**: look for actual PAR/PPFD ratings or a light marketed for plants, not just decoration\n- A basic full-spectrum LED panel or bar light is enough for a shelf of cacti\n\n**Positioning (the most common mistake)**\n\n- Distance: 6-12 inches from the plant tops for most LED panels. Too far and it's useless; too close and it can bleach.\n- Angle: place the light directly above — light from the side makes cacti lean\n- Coverage: a light bar covers a wide shelf; a small round light only covers the plants right under it\n\n**How Long to Run Them**\n\n- 10-14 hours per day in the growing season (spring through fall)\n- 8-10 hours in winter, or match your plants' dormancy needs\n- Use a timer — consistent photoperiod keeps cacti on a natural rhythm\n- Seedlings do well with 14-16 hours of gentle light\n\n**Do Cacti Need a Dark Period?**\n\nYes. Cacti are CAM plants — they take in CO2 at night and process it by day. A 10-14 hour on / 10-14 hour off cycle works with that biology. Don't leave lights on 24/7.\n\n**Heat and Ventilation**\n\n- LEDs run cool, but a light inches above plants can still warm the area — monitor on hot days\n- Good airflow prevents fungal issues, especially on seedlings\n\n**Signs You've Got It Right**\n\n- Compact growth with tight spacing between ribs or areoles\n- Deep green (or natural) color, not pale\n- New spines grow dense and strong\n- Flower buds in the growing season — the ultimate sign the light is working\n\n**What About Grow-Light Kits?**\n\nComplete kits — a panel with a timer and a rack — take the guesswork out of positioning and duration. If you're serious about growing cacti indoors, a small kit pays for itself in the first healthy, flowering season.`,
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}

export function getRelatedPosts(current: string, count = 3): BlogPost[] {
  return posts.filter((p) => p.slug !== current).slice(0, count);
}
